ifneq ($(KERNELRELEASE),)
# kbuild part of makefile
obj-m := laba6.o
ccflags-y += -g
else
# normal makefile
KDIR ?= /lib/modules/uname -r/build

default:
 $(MAKE) -C $(KDIR) M=$$PWD
 cp laba6.ko laba6.ko.unstripped
 $(CROSS_COMPILE)strip -g laba6.ko

clean:
 $(MAKE) -C $(KDIR) M=$$PWD clean
endif